### ISSUE TITLE
web demo blackscreens

### ISSUE THREAD

**Issue by amaramth** [zenorogue/newconformist#2]
http://www.roguetemple.com/z/sims/nconf/

it goes and
```
(index):170 exception thrown: RangeError: Maximum call stack size exceeded,RangeError: Maximum call stack size exceeded
    at wasm-function[4111]:0x3453ee
    at wasm-function[2206]:0x28b104
    at Module.dynCall_viiiiiiiiiiiiiiiiiiiiiiiiiii (http://www.roguetemple.com/z/hyper/rogueviz.js:1:208162)
    at invoke_viiiiiiiiiiiiiiiiiiiiiiiiiii (http://www.roguetemple.com/z/hyper/rogueviz.js:1:333212)
    at wasm-function[4112]:0x3456fe
    at wasm-function[2205]:0x28b0c5
    at Module.dynCall_viiiiiiiiiiiiiiiiiiiiiiiiiiiii (http://www.roguetemple.com/z/hyper/rogueviz.js:1:208315)
    at invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiii (http://www.roguetemple.com/z/hyper/rogueviz.js:1:332809)
    at wasm-function[4113]:0x345a16
    at wasm-function[2204]:0x28b082```

**Comment by zenorogue** [comment]
This is on startup, right? Which browser, operating system, etc.?

**Comment by zenorogue** [comment]
Edit: I seem to get the same error in Chrome, it works in Firefox.

**Comment by zenorogue** [comment]
I have fixed it in Chrome -- please check if it works for you (it seems I needed to clear the cache first, otherwise the old version was used). Thanks!

**Comment by amaramth** [comment]
👍
